### ISSUE TITLE
HTML-CSS-Best-Practice

### ISSUE THREAD

**Issue by sntakirutimana72** [sntakirutimana72/To-Do-list#8]
## Feedback

- The code snippet below could've been made global as more than one code block uses it.
```CSS
  {
    display: flex;
    align-items: center;
  }
```
